name: reco_env
channels:
    - pytorch
    - nvidia
    - conda-forge
    - defaults
dependencies:
  - python=3.10
  - monai=1.3.0
  - easydict=1.9
  - conda-forge::nibabel
  - pip:
      - matplotlib==3.9.0
      - numpy==1.26.4
      - pillow==10.0.1
      - scikit-image==0.24.0
      - scipy==1.14.1
      - torch==2.2.0


